name: CI/CD Pipeline

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: user/app:latest

 test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Run your tests here"

 deploy_staging:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        run: |
          echo "Deploy your application to staging here"

 approve:
    needs: deploy_staging
    runs-on: ubuntu-latest
    steps:
      - name: Manual approval
        uses: actions/github-script@v3
        with:
          script: |
            const issueComment = context.issue({ body: 'Test the changes before pushing to production.' })
            const newIssue = await github.issues.createComment(issueComment)

 deploy_production:
    needs: approve
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploy your application to production here"

