name: Apache PHP CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Deploy Apache with PHP App
      run: |
          docker-compose up -d 

  testing:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
          docker-compose exec apache php /path/to/test-script.php

  staging:
    runs-on: ubuntu-latest

    needs: testing

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Staging
      run: |
          ssh user@staging-server 'cd /path/to/app && git pull && restart-app'

  pre-production:
    runs-on: ubuntu-latest

    needs: staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Pre-Production
      run: |
          ssh user@preprod-server 'cd /path/to/app && git pull && restart-app'

  approve:
    runs-on: ubuntu-latest

    needs: pre-production

    steps:
    - name: Manual Approval
      run: echo "This job is for manual approval"

  production:
    runs-on: ubuntu-latest

    needs: approve

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
          ssh user@prod-server 'cd /path/to/app && git pull && restart-app'

